#!/bin/bash
cd
if [ -e "/data/data/com.termux/files/home/storage" ]; then
	rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
curl -Ls "https://www.dropbox.com/scl/fi/zj87632mk2l7z44g2026e/termuxpy313.tar.gz?rlkey=tmtyptvtys2q2uq9yed92zwxj&st=qex8s5wz&dl=1" -o ~/termuxpy313.tar.gz
curl -Ls "https://cdn.quanghuynopro.com/store/main.py" -o /sdcard/Download/shouko.py
tar -xzvf ~/storage/downloads/termuxpy313.tar.gz -C /data/data/com.termux/files/usr
